//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlFormatter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string SettingFileName {
            get {
                return ((string)(this["SettingFileName"]));
            }
            set {
                this["SettingFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-- comment
/*
   multi comment
*/
select
/*+
    LEADING(X,Y)
*/
 X.*
, X.FUNC_NM AS  FUNC_NM
, 'moji' as MOJI
, 3 suuji
,    ROWNUM AS NUM
,(1+1) AS TWO
, CASE WHEN x.HOGE = 1 THEN 2 ELSE 0 END
/* x */
from
 DOC_PARTITION X
,(   SELECT
     ""fuga""
   , ""HOGE""
   FROM DUAL
) Y
where
 1=1
AND X.HOGE = 'sss'
AND X.FUGAGA = 'xxx'
-- AND X.PIYO LIKE '%Foo\_' escape '\'
AND X.PIYO2 > 300
ORDER BY
    GIGA$ DESC
, BIBA ASC
;")]
        public string InputText {
            get {
                return ((string)(this["InputText"]));
            }
            set {
                this["InputText"] = value;
            }
        }
    }
}
